import { env } from '../config/env.js';

export class GroqService {
  constructor() {
    this.apiKey = env.GROQ_API_KEY;
    this.model = env.GROQ_MODEL || 'llama-3.3-70b-versatile';
    this.candidateModels = [
      this.model,
      'llama-3.3-70b-versatile',
      'llama-3.1-8b-instant'
    ].filter((v, i, a) => a.indexOf(v) === i);
    this.temperature = env.LLM_TEMPERATURE ?? 0.2;
  }

  isAvailable() {
    return Boolean(this.apiKey && this.apiKey.trim().length > 0);
  }

  getSystemPrompt(mode = "auto") {
    return (
      "You are BIS Sahayak V2, an intelligent AI assistant capable of answering general, technical, and regulatory questions naturally and accurately like a modern LLM.\n\n" +
      "Understand the user's intent before answering:\n" +
      "- For greetings, chit-chat, and general knowledge questions (e.g. programming, science, general definitions), answer directly, helpfully, and naturally with clean markdown formatting.\n" +
      "- For BIS/regulatory/standards questions, provide accurate, structured information. Never invent IS standard numbers, QCO mandates, clauses, or legal penalties. If authoritative information is uncertain, clearly state that it requires official verification at www.manakonline.in.\n" +
      "- Maintain conversation context and understand follow-up questions.\n" +
      "- Do not mention internal routing, models, APIs, or database implementation details.\n" +
      "- Provide concise, useful, and properly formatted markdown responses."
    );
  }

  buildMessages({ query, history = [], contextChunks = [] }) {
    const messages = [];

    // System instruction
    messages.push({
      role: 'system',
      content: this.getSystemPrompt()
    });

    // History
    if (Array.isArray(history) && history.length > 0) {
      for (const msg of history) {
        const content = msg.content || msg.text || '';
        if (!content.trim()) continue;
        const role = (msg.role === 'assistant' || msg.role === 'model') ? 'assistant' : 'user';
        messages.push({ role, content });
      }
    }

    // Context chunks if any
    let latestContent = query;
    if (contextChunks && contextChunks.length > 0) {
      const formattedChunks = contextChunks.slice(0, 4).map(c =>
        `[Standard: ${c.standard_id || 'IS'} | Clause: ${c.clause_id || c.section || 'General'} | Page: ${c.page || 1}]:\n${c.content || c.text || ''}`
      ).join('\n---\n');

      latestContent = (
        `AUTHORITATIVE BIS CONTEXT:\n${formattedChunks}\n\n` +
        `USER QUESTION:\n${query}\n\n` +
        `Answer the question using the context above if relevant.`
      );
    }

    messages.push({ role: 'user', content: latestContent });
    return messages;
  }

  async chatCompletion({ query, history = [], mode = "auto", contextChunks = [] }) {
    if (!this.isAvailable()) {
      throw new Error("GROQ_API_KEY is not configured in backend .env.");
    }

    const startTime = Date.now();
    const messages = this.buildMessages({ query, history, contextChunks });
    let lastErr = null;

    for (const modelName of this.candidateModels) {
      try {
        const res = await fetch('https://api.groq.com/openai/v1/chat/completions', {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${this.apiKey}`,
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            model: modelName,
            messages,
            temperature: this.temperature,
            max_tokens: 1024
          }),
          signal: AbortSignal.timeout(10000)
        });

        if (!res.ok) {
          const errData = await res.json().catch(() => ({}));
          throw new Error(errData.error?.message || `Groq API responded with status ${res.status}`);
        }

        const data = await res.json();
        const rawContent = data.choices?.[0]?.message?.content || "";
        // Clean out any <think> reasoning tags if present
        const answer = rawContent.replace(/<think>[\s\S]*?<\/think>/gi, '').trim() || "No answer generated by Groq.";
        const processingTime = Math.round((Date.now() - startTime) / 100) / 10;

        return {
          answer,
          response: answer,
          mode: 'groq',
          model: modelName,
          confidence: null,
          citations: [],
          processing_time: processingTime
        };
      } catch (err) {
        lastErr = err;
        console.warn(`[Groq Model ${modelName} Note] ${err.message}. Trying next candidate...`);
      }
    }

    throw lastErr || new Error("All Groq candidate models failed.");
  }

  async streamCompletion({ query, history = [], mode = "auto", contextChunks = [], res, onDone = null }) {
    if (!this.isAvailable()) {
      throw new Error("GROQ_API_KEY is not configured in backend .env.");
    }

    const startTime = Date.now();
    const messages = this.buildMessages({ query, history, contextChunks });
    let fullText = '';
    let chosenModel = this.model;
    let streamRes = null;

    for (const modelName of this.candidateModels) {
      try {
        const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${this.apiKey}`,
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            model: modelName,
            messages,
            temperature: this.temperature,
            max_tokens: 1024,
            stream: true
          }),
          signal: AbortSignal.timeout(15000)
        });

        if (response.ok) {
          streamRes = response;
          chosenModel = modelName;
          break;
        }
      } catch (err) {
        console.warn(`[Groq Stream ${modelName} Note] ${err.message}`);
      }
    }

    if (!streamRes) {
      throw new Error("Could not initiate streaming with any Groq candidate model.");
    }

    const reader = streamRes.body.getReader();
    const decoder = new TextDecoder('utf-8');
    let buffer = '';

    try {
      while (true) {
        const { value, done } = await reader.read();
        if (done) break;

        buffer += decoder.decode(value, { stream: true });
        const lines = buffer.split('\n');
        buffer = lines.pop() || '';

        for (const line of lines) {
          const trimmed = line.trim();
          if (!trimmed || trimmed.startsWith(':')) continue;
          if (trimmed === 'data: [DONE]') continue;

          if (trimmed.startsWith('data: ')) {
            try {
              const json = JSON.parse(trimmed.slice(6));
              const token = json.choices?.[0]?.delta?.content;
              if (token) {
                // Filter out reasoning tokens if any
                if (!token.includes('<think>') && !token.includes('</think>')) {
                  fullText += token;
                  res.write(`data: ${JSON.stringify({ type: 'token', content: token })}\n\n`);
                }
              }
            } catch (e) {
              // Ignore partial JSON chunks
            }
          }
        }
      }
    } catch (err) {
      console.warn("[Groq Stream Reader Warning]", err.message);
    }

    const processingTime = Math.round((Date.now() - startTime) / 100) / 10;
    const meta = {
      confidence: null,
      citations: [],
      mode: 'groq',
      model: chosenModel,
      processing_time: processingTime,
      done: true
    };

    res.write(`data: ${JSON.stringify({ type: 'done', ...meta })}\n\n`);
    res.end();

    if (typeof onDone === 'function') {
      try {
        onDone(fullText, meta);
      } catch (err) {
        console.warn("[Groq onDone Error]", err.message);
      }
    }
  }
}

export const groqService = new GroqService();
